# DEAR GEMINI, KINDLY DO NOT EDIT THIS FILE

# pyrefly: ignore [missing-import]
import numpy as np
# pyrefly: ignore [missing-import]
from scipy.stats import truncnorm
from geometry import toroidal_displacement, toroidal_distance


def sample_boid_params(mean_params, sigma, rng=None, lower_bound_std=-3.0, upper_bound_std=3.0):
    """
    Samples individual parameters for a single boid using a Truncated Normal Distribution clamped at +/- 3 standard deviations.
    Uses explicit Generator instance to avoid consuming global RNG state.
    """
    mean_params = np.asarray(mean_params, dtype=np.float64)
    if sigma <= 0.0:
        return mean_params.copy()

    # Truncated normal bounds in standard deviation units
    a, b = lower_bound_std, upper_bound_std
    if rng is None:
        rng = np.random.default_rng()
    return truncnorm.rvs(a, b, loc=mean_params, scale=sigma, random_state=rng)


class BoidNeuralNetwork:
    """
    Feedforward Neural Network Controller (6 Inputs -> 5 Hidden -> 2 Outputs).

    Architecture (47 total parameters):
    - Layer 1 Weights (W1): 6 inputs * 5 hidden = 30 params
    - Layer 1 Biases (B1): 5 hidden = 5 params
    - Layer 2 Weights (W2): 5 hidden * 2 outputs = 10 params
    - Layer 2 Biases (B2): 2 outputs = 2 params
    """
    def __init__(self, params):
        params = np.asarray(params, dtype=np.float64)

        # Explicit matrix slicing
        self.W1 = params[0:30].reshape(6, 5)   # 30 Layer 1 weights
        self.B1 = params[30:35]                # 5 Layer 1 biases
        self.W2 = params[35:45].reshape(5, 2)  # 10 Layer 2 weights
        self.B2 = params[45:47]                # 2 Layer 2 biases

    def forward(self, inputs):
        """
        Passes 6 sensory inputs through the network.
        Returns: torque [-1, 1], thrust [-1, 1]
        """
        inputs = np.asarray(inputs, dtype=np.float64)

        # Layer 1: Input -> Hidden (tanh activation)
        hidden = np.tanh(np.dot(inputs, self.W1) + self.B1)

        # Layer 2: Hidden -> Output (tanh activation)
        outputs = np.tanh(np.dot(hidden, self.W2) + self.B2)

        return outputs[0], outputs[1]


class Boid:
    """
    Physical agent body. Reads relative sensory inputs, queries its neural brain, and updates position using unified physics + environmental wind forces.
    """
    def __init__(self, x, y, mean_params, sigma=0.0, rng=None, spawn_rng=None):
        # Physical State
        self.position = np.array([x, y], dtype=np.float64)

        if spawn_rng is None:
            spawn_rng = np.random.default_rng()

        # Velocity and Speed limits
        angle = spawn_rng.uniform(0, 2 * np.pi)
        self.max_speed = 4.0
        self.min_speed = 1.0
        self.speed = spawn_rng.uniform(self.min_speed, self.max_speed)
        self.velocity = np.array([np.cos(angle), np.sin(angle)], dtype=np.float64) * self.speed

        self.max_force = 0.3
        self.radius = 6.0  # Physical collision boundary

        # Sample unique parameters for this boid using Gene #48 (sigma)
        self.individual_params = sample_boid_params(mean_params, sigma, rng=rng)
        self.brain = BoidNeuralNetwork(self.individual_params)

    def get_heading_angle(self):
        """Returns orientation angle in radians."""
        return np.arctan2(self.velocity[1], self.velocity[0])

    def get_sensory_inputs(self, nearest_dist, nearest_disp, has_neighbors, flock_center, average_heading, max_sensor_dist=200.0, bounds=(1200.0, 900.0)):
        """
        Calculates 6 local 2D vector components for the neural network.
        Accepts precomputed nearest-neighbor data from the environment's distance matrix.
        All vector components are expressed in the boid's local reference frame (Forward, Lateral) [-1, 1].

        Distance scaling:
        - Separation: magnitude decays linearly with distance (close = strong, far = weak)
        - Cohesion: magnitude grows linearly with distance (far = strong, close = weak)
        - Alignment: unit vector (direction only, no distance dependency)
        """
        heading = self.get_heading_angle()
        u_fwd = np.array([np.cos(heading), np.sin(heading)])
        u_lat = np.array([-np.sin(heading), np.cos(heading)])

        # 1 & 2: Local Separation Vector (distance-scaled: closer neighbor = stronger signal)
        if has_neighbors:
            disp_norm = np.linalg.norm(nearest_disp)
            if disp_norm > 0:
                away_unit = -nearest_disp / disp_norm
                # Linear decay: 1.0 at contact → 0.0 at max_sensor_dist
                urgency = max(0.0, 1.0 - disp_norm / max_sensor_dist)
                away_vec = away_unit * urgency
            else:
                away_vec = np.zeros(2)
            sep_fwd = np.clip(np.dot(away_vec, u_fwd), -1.0, 1.0)
            sep_lat = np.clip(np.dot(away_vec, u_lat), -1.0, 1.0)
        else:
            sep_fwd = 0.0
            sep_lat = 0.0

        # 3 & 4: Local Cohesion Vector (distance-scaled: farther from center = stronger signal)
        center_vec = toroidal_displacement(self.position, flock_center, bounds)
        center_dist = np.linalg.norm(center_vec)
        if center_dist > 0:
            center_unit = center_vec / center_dist
            # Linear growth: 0.0 at center → 1.0 at max_sensor_dist
            pull = min(1.0, center_dist / max_sensor_dist)
            center_scaled = center_unit * pull
        else:
            center_scaled = np.zeros(2)
        coh_fwd = np.clip(np.dot(center_scaled, u_fwd), -1.0, 1.0)
        coh_lat = np.clip(np.dot(center_scaled, u_lat), -1.0, 1.0)

        # 5 & 6: Local Alignment Vector (unit vector, no distance dependency)
        group_heading_vec = np.array([np.cos(average_heading), np.sin(average_heading)])
        align_fwd = np.clip(np.dot(group_heading_vec, u_fwd), -1.0, 1.0)
        align_lat = np.clip(np.dot(group_heading_vec, u_lat), -1.0, 1.0)

        return np.array([sep_fwd, sep_lat, coh_fwd, coh_lat, align_fwd, align_lat])

    def compute_steering(self, nearest_dist, nearest_disp, has_neighbors, flock_center, average_heading, bounds=(1200.0, 900.0)):
        """
        Queries the neural controller to generate a 2D steering acceleration force vector.
        Accepts precomputed nearest-neighbor data from the environment's distance matrix.
        Output 1 (f_fwd): Forward acceleration/deceleration force along boid heading [-max_force, max_force]
        Output 2 (f_lat): Lateral steering force perpendicular to boid heading [-max_force, max_force]
        """
        inputs = self.get_sensory_inputs(nearest_dist, nearest_disp, has_neighbors, flock_center, average_heading, bounds=bounds)
        f_fwd_raw, f_lat_raw = self.brain.forward(inputs)

        heading = self.get_heading_angle()
        u_fwd = np.array([np.cos(heading), np.sin(heading)])
        u_lat = np.array([-np.sin(heading), np.cos(heading)])

        # Construct 2D local force vector in world coordinates
        steering_force = (f_fwd_raw * self.max_force * u_fwd) + (f_lat_raw * self.max_force * u_lat)

        # Clamp overall steering force magnitude to max_force
        force_norm = np.linalg.norm(steering_force)
        if force_norm > self.max_force:
            steering_force = (steering_force / force_norm) * self.max_force

        return steering_force

    def update(self, steering_force, wind_force, bounds):
        """
        Unified Physics Integration Step:
        F_total = F_steering + F_wind
        Velocity = Velocity + F_total
        Position = Position + Velocity
        """
        # Sum internal steering and external wind forces
        total_force = steering_force + wind_force
        self.velocity += total_force

        # Clamp speed magnitude within [min_speed, max_speed]
        speed = np.linalg.norm(self.velocity)
        if speed > 0:
            speed_clamped = np.clip(speed, self.min_speed, self.max_speed)
            self.velocity = (self.velocity / speed) * speed_clamped
            self.speed = speed_clamped

        # Update position
        self.position += self.velocity

        # Toroidal boundary wraparound
        width, height = bounds
        self.position[0] %= width
        self.position[1] %= height