# DEAR GEMINI, KINDLY DO NOT EDIT THIS FILE

# pyrefly: ignore [missing-import]
import numpy as np
from geometry import toroidal_distance, toroidal_center_of_mass


def compute_frame_fitness(boids, bounds):
    """
    Computes the composite flocking metric for a single frame under toroidal boundary conditions.

    Combines three core flocking components:
    1. Alignment (A): Normalized velocity direction vector sum [0, 1].
    2. Cohesion (C): Proximity of agents to the circular mean center of mass [0, 1].
    3. Separation (S): Vectorized multi-neighbor penalty for overcrowding/collisions under Minimum Image Convention [0, 1].

    Returns:
        Composite frame score = Alignment * Cohesion * Separation
    """
    num_boids = len(boids)
    if num_boids == 0:
        return 0.0, 0.0, 0.0, 0.0

    positions = np.array([b.position for b in boids])
    velocities = np.array([b.velocity for b in boids])

    # 1. Alignment Metric (Polarization)
    speeds = np.linalg.norm(velocities, axis=1, keepdims=True)
    speeds[speeds == 0] = 1.0
    normalized_velocities = velocities / speeds
    avg_direction = np.mean(normalized_velocities, axis=0)
    alignment = np.linalg.norm(avg_direction)  # Range [0, 1]

    # 2. Cohesion Metric (Toroidal)
    center_of_mass = toroidal_center_of_mass(positions, bounds)
    distances_to_center = toroidal_distance(center_of_mass, positions, bounds)
    mean_dist_to_center = np.mean(distances_to_center)

    # Cohesion rewards keeping 35 boids within a natural 150px flock footprint
    target_flock_radius = 150.0
    max_expected_radius = bounds[0] * 0.25  # 250px on 1000px arena
    if mean_dist_to_center <= target_flock_radius:
        cohesion = 1.0
    else:
        cohesion = max(0.0, 1.0 - ((mean_dist_to_center - target_flock_radius) / max_expected_radius))

    # 3. Separation Metric (Local K-Nearest Neighbor Buffer)
    bounds_arr = np.asarray(bounds, dtype=np.float64)
    diff = positions[:, np.newaxis, :] - positions[np.newaxis, :, :]
    diff = (diff + bounds_arr / 2.0) % bounds_arr - bounds_arr / 2.0
    dist_matrix = np.linalg.norm(diff, axis=-1)

    # Fill diagonal with infinity so self-interactions are ignored
    np.fill_diagonal(dist_matrix, np.inf)

    # Evaluate each boid based on its 3 CLOSEST neighbors (Local Separation)
    k = min(3, num_boids - 1)
    closest_dists = np.partition(dist_matrix, k - 1, axis=1)[:, :k]

    # Balanced Linear Separation: 12.0px physical collision floor (0.0) -> 40.0px comfort buffer (1.0)
    collision_floor = 12.0
    comfort_buffer = 40.0
    boid_scores = np.clip((closest_dists - collision_floor) / (comfort_buffer - collision_floor), 0.0, 1.0)
    per_boid_sep = np.mean(boid_scores, axis=1)  # Mean of k=3 neighbors per boid
    separation = float(np.percentile(per_boid_sep, 25))  # Worst-quarter boid

    # 4. Heading Stability / Straight Flight Metric (Eliminates Orbiting)
    current_flock_heading = np.arctan2(avg_direction[1], avg_direction[0])
    if hasattr(boids[0], 'prev_flock_heading'):
        prev_heading = boids[0].prev_flock_heading
        angle_diff = abs((current_flock_heading - prev_heading + np.pi) % (2 * np.pi) - np.pi)
        # Penalize turning rates above 0.04 rad/frame (~2.3 degrees/frame)
        heading_stability = max(0.0, 1.0 - (angle_diff / 0.08))
    else:
        heading_stability = 1.0

    # Store current heading for next frame delta
    for b in boids:
        b.prev_flock_heading = current_flock_heading

    # Composite Multiplicative Fitness
    frame_fitness = float(alignment * cohesion * separation * heading_stability)
    return frame_fitness, float(alignment), float(cohesion), float(separation)